// Author: Jeff.Liu. Actual App callback source with mock IPC, no native actions.
import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';import {SystemEntryController} from '../src/system-entry.ts';
const source=ts.createSourceFile('App.tsx',readFileSync(new URL('../src/App.tsx',import.meta.url),'utf8'),ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);const app=source.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='App');const compile=t=>ts.transpileModule(t,{compilerOptions:{target:ts.ScriptTarget.ESNext}}).outputText;
const pause=(owner='a'.repeat(64),revision=1,paused=true)=>({owner_instance:owner,revision,paused,established:true});
test('T11 migration reads current owner and seeds only fenced unestablished snapshot',async()=>{const calls=[],s=new SystemEntryController();let state={...pause(),established:false,revision:0,paused:false};const value=await s.load(async(name,args)=>{calls.push({name,args});return name==='initialize_notification_pause'?pause():state;},true);assert.equal(value.paused,true);assert.deepEqual(calls,[{name:'get_notification_pause_state',args:{}},{name:'initialize_notification_pause',args:{legacy_paused:true,expected_owner_instance:'a'.repeat(64)}}]);});
test('T11 tray-established state wins migration and explicit CAS uses owner fence',async()=>{const calls=[],s=new SystemEntryController();await s.load(async(name,args)=>{calls.push({name,args});return pause();},false);await s.setPause(async(name,args)=>{calls.push({name,args});return pause('a'.repeat(64),2,false);},false);assert.equal(calls.filter(c=>c.name==='initialize_notification_pause').length,0);assert.deepEqual(calls.at(-1),{name:'set_notification_paused',args:{paused:false,expected_revision:1,expected_owner_instance:'a'.repeat(64)}});});
test('T11 controller cancel and replacement reject old responses without secret error',async()=>{let resolve;const old=new Promise(ok=>resolve=ok);const s=new SystemEntryController();const loading=s.load(async()=>old,false).catch(()=>null);s.cancel();resolve(pause());assert.equal(await loading,null);await s.load(async()=>pause('b'.repeat(64)),false);assert.equal(s.accept(pause()),false);assert.equal(s.accept(pause('b'.repeat(64),0)),false);});
test('T11 actual App focus context never sends competing pause authority',async()=>{const declaration=app.body.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='syncNotificationContext');const calls=[];const args={notificationContextFlight:{current:{sending:false,pending:null}},terminalMounted:{current:true},sessionId:{current:null},pausedRef:{current:true},notificationContextVersion:{current:0},terminalHasInputFocus:()=>false,invoke:async(name,parameters)=>calls.push({name,parameters}),setError(){}};const run=new Function(...Object.keys(args),compile(declaration.getText(source))+';return syncNotificationContext;')(...Object.values(args));run();await new Promise(setImmediate);assert.deepEqual(calls,[{name:'set_agent_notification_context',parameters:{selected:null}}]);});

test('T11 actual App explicit pause callback uses current owner controller and mirrors only accepted snapshot',async()=>{
 const declaration=app.body.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='toggleNotificationPause');assert.ok(declaration,'actual explicit pause callback is required');const calls=[],state={current:pause()},args={notificationPause:{current:new SystemEntryController()},notificationPauseState:state,terminalMounted:{current:true},notificationPauseVersion:{current:0},invoke:async(name,parameters)=>{calls.push({name,parameters});return pause('a'.repeat(64),2,false);},applyNotificationPause(value){state.current=value;},refreshNotificationPause:async()=>{},setError(){}};await args.notificationPause.current.load(async()=>pause(),false);const run=new Function(...Object.keys(args),compile(declaration.getText(source))+';return toggleNotificationPause;')(...Object.values(args));await run();assert.deepEqual(calls,[{name:'set_notification_paused',parameters:{paused:false,expected_revision:1,expected_owner_instance:'a'.repeat(64)}}]);assert.equal(state.current.paused,false);
});
test('T11 actual settings renders explicit default-off fixed accelerator with fallback and error',()=>{
 const text=readFileSync(new URL('../src/SystemEntrySettings.tsx',import.meta.url),'utf8'),compiled=ts.transpileModule(text,{compilerOptions:{target:ts.ScriptTarget.ESNext,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React}}).outputText;const exports={};const React={createElement:(type,props,...children)=>({type,props:props||{},children})};new Function('exports','React','require',compiled)(exports,React,name=>{assert.equal(name,'react');return {__esModule:true,default:React};});const changes=[];const view=exports.default({enabled:false,registered:false,available:true,busy:false,warning:'global_shortcut_unavailable',onChange:value=>changes.push(value)});const nodes=[];function walk(node){if(!node||typeof node!=='object')return;nodes.push(node);node.children?.flat(Infinity).forEach(walk);}walk(view);const input=nodes.find(node=>node.type==='input');assert.ok(input,'visible explicit shortcut checkbox');assert.equal(input.props.checked,false);input.props.onChange({target:{checked:true}});assert.deepEqual(changes,[true]);assert.match(JSON.stringify(view),/CommandOrControl\+Shift\+Y/);assert.match(JSON.stringify(view),/normal YAM window/);assert.match(JSON.stringify(view),/global_shortcut_unavailable/);
});

test('T11 actual shortcut settings late same-owner finally cannot clear newer busy intent',async()=>{
 const declaration=app.body.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='setGlobalShortcut');const pending=[],busy=[],state=[],owner={current:pause()};const args={notificationPauseState:owner,systemEntryVersion:{current:0},systemEntryMutation:{current:0},terminalMounted:{current:true},setSystemEntryBusy:value=>busy.push(value),setSystemEntry:value=>state.push(value),invoke:(name,parameters)=>new Promise((resolve,reject)=>pending.push({name,parameters,resolve,reject})),refreshSystemEntry:async()=>{},setError(){}};const run=new Function(...Object.keys(args),compile(declaration.getText(source))+';return setGlobalShortcut;')(...Object.values(args));const first=run(true),second=run(false);pending[0].resolve({owner_instance:pause().owner_instance,global_shortcut_enabled:true});await first;assert.deepEqual(busy,[true,true]);pending[1].resolve({owner_instance:pause().owner_instance,global_shortcut_enabled:false});await second;assert.deepEqual(busy,[true,true,false]);assert.equal(state.length,1);
});
test('T11 actual explicit pause stale owner success and rejection cannot change UI or refresh new owner',async()=>{
 const declaration=app.body.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='toggleNotificationPause');for(const reject of [false,true]){let settle;const writes=[],errors=[],refresh=[];const owner={current:pause()};const args={notificationPauseState:owner,notificationPauseVersion:{current:0},terminalMounted:{current:true},notificationPause:{current:{setPause:()=>new Promise((resolve,no)=>settle=reject?no:resolve)}},invoke(){},applyNotificationPause:value=>writes.push(value),setError:value=>errors.push(value),refreshNotificationPause:async()=>refresh.push(1)};const run=new Function(...Object.keys(args),compile(declaration.getText(source))+';return toggleNotificationPause;')(...Object.values(args));const waiting=run();owner.current=pause('b'.repeat(64));args.notificationPauseVersion.current++;settle(reject?Error('secret'):pause());await waiting;assert.deepEqual([writes,errors,refresh],[[],[],[]]);}
});

test('T11 actual shortcut conflict refresh cannot show a late error for a replaced owner',async()=>{
 const declaration=app.body.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='setGlobalShortcut');let reject,finishRefresh;const errors=[],owner={current:pause()};const args={notificationPauseState:owner,systemEntryVersion:{current:0},systemEntryMutation:{current:0},terminalMounted:{current:true},setSystemEntryBusy(){},setSystemEntry(){},invoke:()=>new Promise((yes,no)=>reject=no),refreshSystemEntry:()=>new Promise(resolve=>finishRefresh=resolve),setError:value=>errors.push(value)};const run=new Function(...Object.keys(args),compile(declaration.getText(source))+';return setGlobalShortcut;')(...Object.values(args));const waiting=run(true);reject(Error('secret'));await new Promise(setImmediate);owner.current=pause('b'.repeat(64));args.systemEntryVersion.current++;finishRefresh();await waiting;assert.deepEqual(errors,[]);
});

test('T11 current owner event during initial snapshot read remains newest when read resolves',async()=>{let resolve;const s=new SystemEntryController(),waiting=s.load(()=>new Promise(ok=>resolve=ok),false);assert.equal(s.accept(pause('a'.repeat(64),2,true)),false);resolve(pause('a'.repeat(64),1,false));assert.equal((await waiting).revision,2);});

test('T11 actual settings effect reconciles events and disposes late setup without uncaught listen errors',async()=>{
 const effect=app.body.statements.find(n=>ts.isExpressionStatement(n)&&ts.isCallExpression(n.expression)&&n.expression.expression.getText(source)==='useEffect'&&n.expression.arguments[1]?.getText(source)==='[gitOwner]');assert.ok(effect);const callback=effect.expression.arguments[0],listeners=[],writes=[],errors=[],dispose=[];let catches=0;const args={notificationPause:{current:new SystemEntryController()},notificationPauseState:{current:pause()},notificationPauseVersion:{current:0},systemEntryVersion:{current:0},systemEntryMutation:{current:0},terminalMounted:{current:true},setSystemEntryBusy(){},refreshNotificationPause(){},refreshSystemEntry(){},applyNotificationPause:value=>writes.push(value),setSystemEntry:value=>writes.push(value),setError:value=>errors.push(value),listen:(name,handler)=>{listeners.push({name,handler});return {then(fn){fn(()=>dispose.push(name));return {catch(){catches++}}}}}};const setup=new Function(...Object.keys(args),compile('const setup='+callback.getText(source))+';return setup;')(...Object.values(args));const cleanup=setup();await args.notificationPause.current.load(async()=>pause(),false);args.notificationPauseState.current=pause();listeners[0].handler({payload:pause('a'.repeat(64),2,false)});assert.equal(writes.length,1);cleanup();listeners[0].handler({payload:pause('a'.repeat(64),3,true)});assert.equal(writes.length,1);assert.equal(dispose.length,2);assert.equal(catches,2,'both native event subscriptions must handle failure');
});

test('T11 delayed refresh never replaces a newer already accepted owner pause revision',async()=>{const s=new SystemEntryController();await s.load(async()=>pause('a'.repeat(64),1,false),false);let resolve;const waiting=s.load(()=>new Promise(ok=>resolve=ok),false);assert.equal(s.accept(pause('a'.repeat(64),3,true)),true);resolve(pause('a'.repeat(64),2,false));assert.equal((await waiting).revision,3);assert.equal((await waiting).paused,true);});

test('T11 actual refresh and mirror do not roll back an accepted event while snapshot is pending',async()=>{let finish;const writes=[],errors=[],controller=new SystemEntryController();await controller.load(async()=>pause('a'.repeat(64),1,false),false);const args={notificationPause:{current:controller},notificationPauseState:{current:pause('a'.repeat(64),1,false)},notificationPauseVersion:{current:0},pausedRef:{current:false},terminalMounted:{current:true},invoke:()=>new Promise(resolve=>finish=resolve),setNotificationsPaused:value=>writes.push(value),localStorage:{setItem:(key,value)=>writes.push({key,value})},setError:value=>errors.push(value)};const code=['refreshNotificationPause','applyNotificationPause'].map(name=>app.body.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text===name).getText(source)).join('\n');const actual=new Function(...Object.keys(args),compile(code)+';return {refreshNotificationPause,applyNotificationPause};')(...Object.values(args));const refreshing=actual.refreshNotificationPause();assert.equal(controller.accept(pause('a'.repeat(64),3,true)),true);actual.applyNotificationPause(pause('a'.repeat(64),3,true));finish(pause('a'.repeat(64),2,false));await refreshing;assert.equal(args.notificationPauseState.current.revision,3);assert.equal(args.notificationPauseState.current.paused,true);assert.equal(writes.at(-1).value,'true');assert.deepEqual(errors,[]);});
